---
wandb:
  flag: True
  project_name: caps
  entity: sptw88

dataset:
  root_path: "/media/sien/DATA/DATA/dataset"
  interval_minutes: 60
  img_size: 572
  train:
    batch_size: 3
    date_from: '20200601'
    date_to: '20220831'
    shuffle: True

  eval:
    batch_size: 3
    date_from: '20230601'
    date_to: '20230831'
    shuffle: True

fit:
  model: 'unet'
  model_save_flag: True                   # True: save model, False: not save model
  train_flag: True
  model_save_path: "/media/sien/DATA/weight"

  test_mode: 'cal_loss' #cal_loss-> score, visible->plot, maskedvisible-> cal mask & show

  state_dict_path: '/media/sien/DATA/weight/unet/BEST_unet_20200601_20230731_imgsize572.pt'


  learning_rate: 5e-5  # 5e-5
  weight_decay: 2e-2
  epochs: 100
  loss: MSE
  optimizer: Adam

  eval_flag: True
  eval_interval: 5
