---
wandb:
  flag: True
  project_name: caps
  entity: sptw88

dataset:
  root_path: "/media/sien/DATA/DATA/dataset"
  interval_minutes: 60
  img_size: 224
  train:
    batch_size: 16
    date_from: '20200601'
    date_to: '20200602'
    shuffle: True

  eval:
    batch_size: 16
    date_from: '20230801'
    date_to: '20230831'
    shuffle: False

fit:
  model: 'resunetplus'
  model_save_flag: False                   # True: save model, False: not save model
  train_flag: False
  model_save_path: "/media/sien/DATA/weight"

  test_mode: 'maskedvisible' #score-> cal_loss, visible->plot, maskedvisible-> cal mask & show

  state_dict_path: '/media/sien/DATA/weight/resunetplus/BEST_resunetplus_20210601_20220830_imgsize224.pt'


  learning_rate: 5e-5  # 5e-5
  weight_decay: 2e-2
  epochs: 100
  loss: MSE
  optimizer: Adam

  eval_flag: True
  eval_interval: 5
