---
wandb:
  flag: True
  project_name: ir2rr
  entity: munjonghyeon

dataset:
  root_path: "/home/jh/data/"
  img_size: 284

  seq:
    is_seq: False
    sequence_len: 3
    ir_only: True

  train:
    interval_minutes: 120
    batch_size: 8
    date_from: '20200601'
    date_to: '20220831'
    shuffle: True

  eval:
    interval_minutes: 120
    batch_size: 4
    date_from: '20230601'
    date_to: '20230831'
    shuffle: False

fit:
  model: unet
  dropout_is: True
  dropout_p: 0.2
  model_save_flag: True                   # True: save model, False: not save model
  model_save_path: "/home/jh/data/models/GK2A"

  train_flag: True
  learning_rate: 1e-4  # 5e-5
  weight_decay: 2e-2
  epochs: 100
  loss: MSE
  optimizer: Adam

  eval_flag: True
  eval_interval: 1
